on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Stuff
        run: |
          mkdir -p www/_site
          cat > www/_site/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>GH Pages deploy test</title>
            </head>
            <body>
              <p>Testing, testing, 1, 2, 3, 4.</p>
            </body>
          </html>
          EOL
      - name: Deploy
        if: success()
        #uses: Cecilapp/GitHub-Pages-deploy@master
        run: |
          REPONAME="$(echo $GITHUB_REPOSITORY| cut -d'/' -f 2)"
          OWNER="$(echo $GITHUB_REPOSITORY| cut -d'/' -f 1)"
          GHIO="${OWNER}.github.io"
          # target branch
          if [[ "$REPONAME" == "$GHIO" ]]; then
            TARGET_BRANCH="master"
          else
            TARGET_BRANCH="gh-pages"
          fi
          # build dir
          if [ -z "$BUILD_DIR" ]; then
            BUILD_DIR="_site"
          fi

          echo "### Started deploy to $GITHUB_REPOSITORY/$TARGET_BRANCH"

          # remove the ending slash if exists
          BUILD_DIR=${BUILD_DIR%/}
          mkdir -p $HOME/$BUILD_DIR
          cp -R $BUILD_DIR/* $HOME/$BUILD_DIR/
          cd $HOME
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$EMAIL"
          echo 1
          if [ -z "$(git ls-remote --heads https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git ${TARGET_BRANCH})" ]; then
            git clone --quiet https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git $TARGET_BRANCH > /dev/null
            cd $TARGET_BRANCH
            git checkout --orphan $TARGET_BRANCH
            git rm -rf .
            echo "$REPONAME" > README.md
            git add README.md
            git commit -a -m "Create $TARGET_BRANCH branch"
            git push origin $TARGET_BRANCH
            cd ..
          else
            git clone --quiet --branch=$TARGET_BRANCH https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git $TARGET_BRANCH > /dev/null
          fi
          echo 2
          cp -R $TARGET_BRANCH/.git $HOME/.git
          rm -rf $TARGET_BRANCH/*
          cp -R $HOME/.git $TARGET_BRANCH/.git
          cd $TARGET_BRANCH
          cp -Rf $HOME/${BUILD_DIR}/* .
          # custom domain?
          if [ ! -z "$CNAME" ]; then
            echo "Add custom domain file"
            echo "$CNAME" > CNAME
          fi
          # .nojekyll
          if [ "$JEKYLL_SITE" != "YES" ]; then
            echo "Disable Jekyll"
            touch .nojekyll
          fi
          # Nothing to deploy?
          if [ -z "$(git status --porcelain)" ]; then
            echo "Nothing to deploy"
          else
            echo 3
            git add -Af .
            echo 4
            git commit -m "$GITHUB_ACTOR published a site update"
            echo 5
            git push -fq origin $TARGET_BRANCH > /dev/null
          fi

          echo "### Finished deploy"
        env:
          EMAIL: ryan@murage.ca
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: www/_site/
