on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Stuff
        run: |
          mkdir -p www/_site
          cat > www/_site/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>GH Pages deploy test</title>
            </head>
            <body>
              <p>Testing, testing, 1, 2, 3, 4.</p>
            </body>
          </html>
          EOL
      - name: Deploy
        if: success()
        #uses: Cecilapp/GitHub-Pages-deploy@master
        run: |
          git ls-remote --heads https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git ${TARGET_BRANCH}
          REPONAME="$(echo $GITHUB_REPOSITORY| cut -d'/' -f 2)"
          OWNER="$(echo $GITHUB_REPOSITORY| cut -d'/' -f 1)"
          GHIO="${OWNER}.github.io"
          # target branch
          if [[ "$REPONAME" == "$GHIO" ]]; then
            TARGET_BRANCH="master"
          else
            TARGET_BRANCH="gh-pages"
          fi
          echo $TARGET_BRANCH
        env:
          EMAIL: ryan@murage.ca
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: www
